version: 0.2

phases:
  install:
    commands:
      - echo Installing Checkov...
      - pip3 install checkov
      - echo Installing Terraform...
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  build:
    commands:
      - echo Navigating to terraform directory...
      - cd terraform
      - echo Initializing Terraform...
      - terraform init
      - echo Creating Terraform Plan...
      - terraform plan -out=tfplan
      - echo Converting plan to JSON...
      - terraform show -json tfplan > plan.json
      - echo Running Checkov Scan...
      - checkov -f main.tf || true
      - echo Uploading plan.json to S3...
      - aws s3 cp plan.json s3://iac-artifacts-srikar-1234/plans/plan.json
      - echo Upload complete!
      
  post_build:
    commands:
      - echo ✅ Build completed successfully
      - echo 📁 Plan uploaded to s3://iac-artifacts-srikar-1234/plans/plan.json
      - echo ⏳ Lambda will now analyze the plan...

artifacts:
  files:
    - terraform/plan.json